export const fonts = [
    "Arial",
    "Verdana",
    "Times New Roman",
    "Courier New",
    "Georgia",
    "Palatino",
    "Garamond",
    "Bookman",
    "Comic Sans MS",
    "Trebuchet MS",
    "Arial Black",
    "Impact",
    "Lucida Console",
    "Tahoma",
    "Geneva",
    "Helvetica",
    "Lucida Sans Unicode",
    "Verdana",
    "Courier New",
    "Brush Script MT",
    "Old English Text MT",
    "Papyrus",
    "Segoe Print",
    "Segoe Script",
    "Segoe UI",
    "Segoe UI Symbol",
    "Book Antiqua",
    "Century Gothic",
    "Copperplate",
    "Copperplate Gothic Light",
    "Copperplate Gothic Bold",
    "Copperplate Gothic",
  ];